FROM public.ecr.aws/lambda/python:3.11                                                                                                                                                                                            
                                                                                                                                                                                                                                    
  RUN yum install -y gcc make wget tar && \                                                                                                                                                                                         
      wget http://ftp.gnu.org/gnu/glpk/glpk-5.0.tar.gz && \                                                                                                                                                                         
      tar -xzf glpk-5.0.tar.gz && \                                                                                                                                                                                                 
      cd glpk-5.0 && ./configure && make && make install && \                                                                                                                                                                       
      cd .. && rm -rf glpk-5.0 glpk-5.0.tar.gz && \                                                                                                                                                                                 
      yum clean all                                                                                                                                                                                                                 
                                                                                                                                                                                                                                    
  COPY requirements.txt .                                                                                                                                                                                                           
  RUN pip install --no-cache-dir -r requirements.txt                                                                                                                                                                                
                                                                                                                                                                                                                                    
  COPY mix_attempt1_celulose_lambda.py .                                                                                                                                                                                            
  COPY lambda_function.py .                                                                                                                                                                                                         
                                                                                                                                                                                                                                    
  CMD ["lambda_function.lambda_handler"]
