            --function-name dashboard-mix-lambda \                                                       
              --image-uri ${{ steps.login-ecr.outputs.registry }}/dashboard-mix-producao:latest
